### PR TITLE
Master

### PR DESCRIPTION
**Pull request by thierryc**
Replace class if filter by a capability if filter….

[layer class] == MSLayerGroup

replace by :
if(typeof layer.style == "undefined" || typeof layer.style().fills ==
"undefined")

### CODE REVIEW

**Comment by thierryc** [comment]
#19

**Comment by rzamoramty** [comment]
how can we install this fix?

**Comment by thierryc** [comment]
Get my version on my git repo.

**Comment by thierryc** [comment]
Add new menu for Select Fond and Color. (no short cut)
untitled

**Comment by thierryc** [comment]
Thank you @ahmedmigo

**Pull request merged**
