### PR TITLE
add MSSymbolMaster to the list of object.

### PR DESCRIPTION
**Pull request by thierryc**
347

```
// Is it an MSSymbolMaster?
if([obj class] == MSSymbolMaster) {
for(var i = 0; i < obj.layers().count(); i++)
{
layer = obj.layers().objectAtIndex(i);
handleObject(layer, attr, fn);
}
return;
}
```

### CODE REVIEW

**Comment by thierryc** [comment]
MSSymbolMaster fix select same border color for me.

**Comment by thierryc** [comment]
add counter feedback 
feedback

**Comment by thierryc** [comment]
select

**Comment by thierryc** [comment]
#17

**Comment by pterisaur** [comment]
This new version works, thank you!

**Comment by wonderbit** [comment]
Thanks @thierryc ! 👍👍👍

**Comment by thierryc** [comment]
You're welcome @wonderbit. I already add auto update to my [plugin find-and-replace] (https://github.com/thierryc/Sketch-Find-And-Replace). 

I can add it to sketch-select-similar-layers too…

**Pull request merged**
